services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QUEUE=blog_processing_queue
    command: python3 main.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health_check || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-queue-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - elasticsearch
      - fastapi
    # ports:
    #   - "9181:9181"  # Uncomment this line if you want to expose the port for rq-dashboard
    environment:
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QUEUE=blog_processing_queue
    command: supervisord -c supervisord.conf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://fastapi:8000/health_check || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
