version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QUEUE=blog_processing_queue
    command: python3 main.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200/_cat/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:alpine"
    depends_on:
      - elasticsearch
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-queue-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - fastapi
      - elasticsearch
    environment:
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - WORKERS_COUNT=1
      - QUEUE=blog_processing_queue
    command: python3 consumer.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200/_cat/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
